### ISSUE TITLE
please add tools in panel model

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_mbzirc#25]
@cretaceous-creature ?
http://www.mbzirc.com/assets/files/MBZIRC-Challenge-Description-Document-V2-7SEP2015.pdf says
```
• A set of 6 tools are placed adjacent to the valve stem, as shown in Figure 4. One of these
6 tools is appropriate for operating the valve stem.
• The UGV will analyze the valve stem and select the appropriate tool to close the valve
stem from the set of provided tools. These tools are standard wrenches that follow the
ISO 7738 standards, and range in size between 10mm and 19mm. The valve stem and the
set of tools to be used in this challenge are shown in Figures 4 and 5 respectively. 
```

**Comment by cretaceous-creature** [comment]
We did not find the ISO7738 standards wrench neither from the store nor the
shop,
instead we use a similar one with range in size of 11mm, 13mm, 15mm, 17mm,
19mm.
I found some similar wrench cad files from GrabCad but it is not the same.
Perhaps I have to draw the cad of those wrenches.


2016-01-13 23:03 GMT+08:00 Kei Okada <notifications@github.com>:

**Comment by cretaceous-creature** [comment]
Tomorrow I will add the wrench download from grabcad and see if that is ok.

2016-01-13 23:26 GMT+08:00 Xiangyu Chen <xychen@jsk.imi.i.u-tokyo.ac.jp>:

**Comment by k-okada** [comment]
http://www.bhg.com/shop/wiha-wiha-40088-roll-up-combination-wrench-set-14-piece-pd6bfdf01e30a671c89593bd9152d7379.html
?

http://www.amazon.co.uk/Bahco-111MSET12-Combination-Spanner-Metric/dp/B000VD6YNS
?



2016年1月14日木曜日、Chen<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> We did not find the ISO7738 standards wrench neither from the store nor the
> shop,
> instead we use a similar one with range in size of 11mm, 13mm, 15mm, 17mm,
> 19mm.
> I found some similar wrench cad files from GrabCad but it is not the same.
> Perhaps I have to draw the cad of those wrenches.
>
>
> 2016-01-13 23:03 GMT+08:00 Kei Okada <notifications@github.com>:
>
> > @cretaceous-creature <https://github.com/cretaceous-creature> ?
> >
> >
> http://www.mbzirc.com/assets/files/MBZIRC-Challenge-Description-Document-V2-7SEP2015.pdf
> > says
> >
> > • A set of 6 tools are placed adjacent to the valve stem, as shown in
> Figure 4. One of these
> > 6 tools is appropriate for operating the valve stem.
> > • The UGV will analyze the valve stem and select the appropriate tool to
> close the valve
> > stem from the set of provided tools. These tools are standard wrenches
> that follow the
> > ISO 7738 standards, and range in size between 10mm and 19mm. The valve
> stem and the
> > set of tools to be used in this challenge are shown in Figures 4 and 5
> respectively.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/tongtybj/mbzirc/issues/25>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tongtybj/mbzirc/issues/25#issuecomment-171330273>.
>


-- 
--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
This is what we have now.

2016-01-13 23:35 GMT+08:00 Kei Okada <notifications@github.com>:

**Comment by cretaceous-creature** [comment]
@tongtybj 
http://www.amazon.co.jp/%E3%83%90%E3%83%BC%E3%82%B3-Combination-Spanner-111M-14T/dp/B000VCZV9C/ref=sr_1_fkmr0_2?ie=UTF8&qid=1452699823&sr=8-2-fkmr0&keywords=Bahco+111MSET

**Comment by cretaceous-creature** [comment]
![Uploading image.png…]()

**Comment by cretaceous-creature** [comment]
![image](https://cloud.githubusercontent.com/assets/8966553/12299200/9af3200a-ba50-11e5-895d-48b2e7f53c11.png)

**Comment by k-okada** [comment]
On Thu, Jan 14, 2016 at 12:41 AM, Chen <notifications@github.com> wrote:

> This is what we have now.
>

if you have these, they are iso 7738 standards

--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
http://www.tracepartsonline.net/(S(lc043l5huumbzeiyogekzfk3))/PartDetails.aspx?Class=FACOM&clsid=/F_FACOM/FACOM.050/FACOM.050.010/&ManID=FACOM&PartFamilyID=10-18072008-079306&PartID=10-18072008-079306&SrchRsltId=13&SrchRsltType=0

http://www.tracepartsonline.net/(S(lc043l5huumbzeiyogekzfk3))/PartsDefs/Production/FACOM/10-18072008-079306/documents/F08_page_130.pdf

I found the CAD of wrenches that follow ISO7738

2016-01-14 1:49 GMT+09:00 Kei Okada <notifications@github.com>:

**Comment by cretaceous-creature** [comment]
The origin is not well aligned, we need the origin to be the centroid of
the circle...
[image: 埋め込み画像 1]
[image: 埋め込み画像 2]

2016-01-14 11:31 GMT+09:00 Xiangyu Chen <xychen@jsk.imi.i.u-tokyo.ac.jp>:

>
> http://www.tracepartsonline.net/(S(lc043l5huumbzeiyogekzfk3))/PartDetails.aspx?Class=FACOM&clsid=/F_FACOM/FACOM.050/FACOM.050.010/&ManID=FACOM&PartFamilyID=10-18072008-079306&PartID=10-18072008-079306&SrchRsltId=13&SrchRsltType=0
>
>
> http://www.tracepartsonline.net/(S(lc043l5huumbzeiyogekzfk3))/PartsDefs/Production/FACOM/10-18072008-079306/documents/F08_page_130.pdf
>
> I found the CAD of wrenches that follow ISO7738
>
> 2016-01-14 1:49 GMT+09:00 Kei Okada <notifications@github.com>:
>

**Comment by k-okada** [comment]
```
[image: 埋め込み画像 1]
[image: 埋め込み画像 2]
```
fail to embed images?

**Comment by cretaceous-creature** [comment]
![image](https://cloud.githubusercontent.com/assets/8966553/12323106/15c4b7e8-bafc-11e5-9684-f7baac648fa2.png)
![image](https://cloud.githubusercontent.com/assets/8966553/12323109/1b5ca13e-bafc-11e5-922a-896912e3601b.png)

**Comment by cretaceous-creature** [comment]
And for the 5NM torque, the new gazebo seems to have the function of apply torque. Not sure of how to use that.
![111](https://cloud.githubusercontent.com/assets/8966553/12323152/61c4090a-bafc-11e5-8107-cd78cebeb575.jpg)

**Comment by cretaceous-creature** [comment]
I have added the wrench, but for the 5NM of the stem, I have not come up with a solution yet.
I tried the feature of gazebo6 of applying the torque, but seems nothing happend...
The panel and the stem are two different link and the stem is coming out slowly..
![111](https://cloud.githubusercontent.com/assets/8966553/12323853/ee135d52-bb01-11e5-99a2-62dad4c5df41.jpg)
![222](https://cloud.githubusercontent.com/assets/8966553/12323855/f4ee391c-bb01-11e5-9c45-622e23695b0b.jpg)
