### ISSUE TITLE
arena model

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_mbzirc#26]
- please put road, ground, stat area, goal area as different links, this allow us to check if mission completed or not more easily
- please set the top surface of the road to be 0 height (z = 0)
- even if the level of top surface of road ground are differ, that is ok. or maybe that is more realistic? https://github.com/tongtybj/mbzirc/issues/16#issuecomment-171140798

**Comment by tongtybj** [comment]
So it seems like the old arena version is more suitable for this request?
Or how should I modify the new arena version, should I set several link
without visible elements inside the arena model(e.g. link: "road", "pad",
"ground", etc)?

2016-01-14 12:17 GMT+09:00 Kei Okada <notifications@github.com>:
