### ISSUE TITLE
task 3を試してみてください。

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_mbzirc#56]
@haraduka 岡田です。
おそくなりました。
https://github.com/start-jsk/jsk_mbzirc
みて環境をセットアップして、してみてください。

また、
https://github.com/start-jsk/jsk_mbzirc/tree/master/jsk_mbzirc_tasks/launch
https://github.com/start-jsk/jsk_mbzirc/tree/master/jsk_mbzirc_tasks/test
にtask_3 がないので作ってみてください。

わからないことがあったら、ここに返事してみてください。

**Comment by haraduka** [comment]
ありがとうございます。
まず一つ質問なのですが、how to compileをやっても、jsk_mbzircのこのリポジトリはcloneされないと思うのですが、このリポジトリはどこに配置することを想定しているのですか？僕はhow to compileで作ったsrc以下にgit cloneしてきてしまったのですが。つまり、src以下にhusky, husky_simulator, universal_robot, jsk_mbzircがある状況です。

**Comment by k-okada** [comment]
お，そうですね．
https://github.com/start-jsk/jsk_mbzirc/pull/57
でどうでしょうか．

**Comment by haraduka** [comment]
すべて動きました。ありがとうございます。

**Comment by tongtybj** [comment]
@k-okada 
About the movement of the "treasure" objects in task3, I think the large one is static after reading the following sentence in the challenge description(http://www.mbzirc.com/assets/files/MBZIRC-Challenge-Description-Document-V2-7SEP2015.pdf). 
"Shortly before the start whistle 10 moving and 10 stationary small objects, and 3** stationary** large objects will appear in the arena."

**Comment by k-okada** [comment]
I see, and the large objects should not move,
https://github.com/start-jsk/jsk_mbzirc/blob/master/jsk_mbzirc_common/gazebo_model/world/mbzirc_arena_task_3.world#L236
it it moving, please fix the code. Maybe @haraduka can do this.

--
◉ Kei Okada

**Comment by haraduka** [comment]
n？？？　The large objects seem like not moving.
I cannot understand what to rewrite.

**Comment by k-okada** [comment]
if that is not moving, that's ok.

Could you put the team of robots in task3 gazebo simulation?

--
◉ Kei Okada

**Comment by tongtybj** [comment]
@haraduka 

you are right.
It seem that the problem was fixed by #33

**Comment by haraduka** [comment]
@k-okada 英語で長い文章書くのは苦手なので日本語で。jsk_mbzirc_task1.launchをjsk_mbzirc_task3.launchにcopyし、quadrotor uavの部分の記述をさらに2つ追加しました。ついでにns="model1"とかを追加して名前衝突しないようにしました。かつ、なんかquadrotorがalready existだと言われるのでurdfファイルも複製してnameの部分をそれぞれ変更しました。ですが依然SpawnModel: Failure - model name quadrotor already exist.のErrorが起きるので困っています。ちょっとよくわからないのでヒントをください

**Comment by k-okada** [comment]
できたところまででpull requestを送ってください．タイトルにWIPと書いておけば皆理解してくれます．
http://www.slideshare.net/asuenami/wip-pr

--
◉ Kei Okada


2016-01-29 16:45 GMT+09:00 Kento Kawaharazuka <notifications@github.com>:

**Comment by tongtybj** [comment]
@haraduka 

hector_quadcopter_gazebo下の
launch/spawn_two_quadrotors.launch
が参考になると思います。

**Comment by haraduka** [comment]
@tongtybj ありがとうございます。
@k-okada pqしました

**Comment by furushchev** [comment]
done by https://github.com/start-jsk/jsk_mbzirc/pull/76
