### ISSUE TITLE
destroy robot if it hit to the ground

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_mbzirc#62]

**Comment by tongtybj** [comment]
what is the meaning of "destroy"? It is easy to disable all command about the drone's motor when it hit to the ground unusually .

**Comment by cretaceous-creature** [comment]
I think it means disable....  got only one chance for landing...

2016-04-12 21:30 GMT+08:00 趙 漠居 <notifications@github.com>:

**Comment by tongtybj** [comment]
Please check pull request #65.

**Comment by k-okada** [comment]
＞disable all command about the drone's motor when it hit to the ground

that's correct, but I also think it will be fun if the drone actually
broken into pieces when  it hit to the ground ;-9

--
◉ Kei Okada
