### ISSUE TITLE
[Feature Request] Enable Wiki

### ISSUE THREAD

**Issue by furushchev** [start-jsk/jsk_mbzirc#75]
I want to use to summarize & discuss about the details of contest rules.

**Comment by furushchev** [comment]
@k-okada Please enable this feature if there is no problem. (I don't have right to do so.)

**Comment by k-okada** [comment]
created

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada I can now go to wiki page! Thank you!
