### ISSUE TITLE
travis log 4MB limitation

### ISSUE THREAD

**Issue by cretaceous-creature** [start-jsk/jsk_mbzirc#79]
@k-okada  Okada sensei, I met the issue of travis 4 mb log limitation, 
is there anyway to solve it? 
Error:
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

**Comment by tongtybj** [comment]
@furushchev 
How did you fix this problem. 
@cretaceous-creature 
May the travis.yaml in origin/master branch can give some hints, since we met the same problem in the past.

**Comment by cretaceous-creature** [comment]
maybe rebuild the travis?

2016-06-02 16:01 GMT+09:00 趙 漠居 <notifications@github.com>:

**Comment by k-okada** [comment]
comment out
https://github.com/start-jsk/jsk_mbzirc/blob/master/.travis.yml#L57-L60
and/or, run
catkin config --merge-devel before
https://github.com/start-jsk/jsk_mbzirc/blob/master/.travis.yml#L52


--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
thank you very much

2016-06-02 18:37 GMT+09:00 Kei Okada <notifications@github.com>:

> comment out
> https://github.com/start-jsk/jsk_mbzirc/blob/master/.travis.yml#L57-L60
> and/or, run
> catkin config --merge-devel before
> https://github.com/start-jsk/jsk_mbzirc/blob/master/.travis.yml#L52
>
>
> --
> ◉ Kei Okada
>
>
