### ISSUE TITLE
合宿

### ISSUE THREAD

**Issue by furushchev** [start-jsk/jsk_mbzirc#89]
確認事項
- [ ] アルファード一日保険
  - 25日は稲葉先生をお送りするタスクあり
- [ ] ハイエース？トラック（屋根付き）？公用車？
- [ ] トヨタレンタリースハイエースレンタル可能か確認
- [ ] 積載量について(特にhrp2の高さ要注意)
- [ ] デスクトップPCを何台持って行くか？
- [ ] 会場の電源について(問い合わせ中) => あり

**Comment by furushchev** [comment]
持って行くモノリスト

- [ ] タスク1ヘリポート?（できていれば）
- [ ] タスク2セット
  - [ ] レンチ
  - [ ] 板
- [ ] タスク3カラー板的なもの？（あれば）
- [ ] HRP2 with 台車
- [ ] HRP2充電器
- [ ] ドローン
  - へび
  - 何か
- [ ] ドローン充電器
- [ ] デスクトップPC
  - Z640とか（要変更）
- [ ] ディスプレイ
- [ ] ノートPC
  - P50
- [ ] 発電機
- [ ] コードリール
- [ ] 電源タップ
- [ ] ガソリン携行缶
- [ ] ビデオカメラ(実験様子撮影・クオリフィケーション動画作成用)
- [ ] ビデオカメラ充電器
- [ ] nighthawk
- [ ] lan switch
- [ ] lan cable
- [ ] 机？

**Comment by tongtybj** [comment]
古田君

まとめてくれてありがとう。

各項目で個数とかも明記したいから、
googleのプレーシートのほうがいいかな？
溝花君に作ってもらったけど、
できたかな？


2016年7月14日 13:30 Furushchev <notifications@github.com>:

**Comment by tongtybj** [comment]
木村君、溝花君

githubのメールは届いていくるかな。

2016年7月14日 16:02 Bakui Chou <chou@jsk.imi.i.u-tokyo.ac.jp>:

**Comment by tongtybj** [comment]
追加で

- []作業工具
- []ラップトップバッテリ(19V 10000mAh)

**Comment by mizmizo** [comment]
バクイさん

僕は届いています。

2016年7月14日 16:04 趙 漠居 <notifications@github.com>:

**Comment by mizmizo** [comment]
googleスプレッドシートでも管理表をすぐ作るのでお待ちください。

**Comment by k-kimura** [comment]
届いてなかったですね．
watchにしたのでこれから届くとおもいます．

**Comment by k-kimura** [comment]
> - [ ] 積載量について(特にhrp2の高さ要注意)

7/17現時点でのHRP2W_MBZIRC(hrp2018)の大きさと重さの見積り

幅: 640 \[mm\]
奥行き: 920 \[mm\]
高さ: 1260 \[mm\] (＝＞ multisenseのヘルメットを外せば 1150 \[mm\]に縮まる)

体重: 全部で約100 \[kg\]
＝＞
約45 \[kg\] (hrp2上半身 + 頭multisense + 腰バッテリ)
\+ 約30 \[kg\] (台車)
\+ 約25 \[kg\] (その他フレーム + velodyneレーザ + hokuyoレーザ + nighthawk + 台車バッテリなど)

**Comment by tongtybj** [comment]
@k-kimura @cretaceous-creature 
>  - [ ] 積載量について(特にhrp2の高さ要注意)
運搬時は上半身を台車から外した方いいのでは？外した時の問題はなんだろう

**Comment by k-kimura** [comment]
> 運搬時は上半身を台車から外した方いいのでは？外した時の問題はなんだろう

個人的には車のスペース的に載せられるのであれば，
台車とつながったまま運ぶのが，
- 326で台車を外す作業
- 合宿場で再び台車をつけ直す作業
- hrp2体内から台車のほうにいってるケーブルとかを取り外す作業

の手間が省けて良いのかとおもってますが，
容量的に厳しければ外してもいいとおもいます．

ただ，外す場合はhrp2上半身をどのように車に載せるかが鍵になります．
- hrp2上半身を移動クレーンで吊って，移動クレーン毎車に載せるのか
- hrp2上半身のみの状態で車に置くのか(＝＞ この場合，だいぶ不安定だとおもうので車の荷台に固定する工夫が必要)

**Comment by inabajsk** [comment]
トヨタレンタリースが八王子に無いか調べて
本三の近くのトヨタレンタリースのハイエースを借りるのが
よい気がする．
バン型の車へ椅子に座らせた
HRP2を運ぶためのスロープを研究室で買ってあります．
皆は知っているかな？
どこかにあるはず，そのスロープで
車輪がついたままHRP2-18を載せてゆくのがよい気がします．

１０年ほど前は
326にもっていった茶色の椅子にHRP2を座らせた状態で
アルファードに積みこんで，秋葉原などへよく
運びこんでいました．

稲葉



2016年7月17日 17:04 Kohei Kimura <notifications@github.com>:

**Comment by k-kimura** [comment]
> 車輪がついたままHRP2-18を載せてゆくのがよい気がします．

そうですね，18号機は車輪付きなのでそのまま車に載せるのが良さそうです．

> HRP2を運ぶためのスロープを研究室で買ってあります．

こちらのスロープ探してみましょう ＞ @mizmizo

**Comment by cretaceous-creature** [comment]
はい、そっちのほうか持ちやすいだと思います。。


2016年7月17日 17:40 Kohei Kimura <notifications@github.com>:

**Comment by inabajsk** [comment]
スロープについてみたことがないかもしれないので

http://www.scrio.co.jp/store/categories/wheelchair/portable-slope/6376.html

にあるように折り畳みして持ち歩けるものです．
８階工作室か，８３B1か，３号館地下，７３B2かにある気がする．
車輪部分をはずすのは辞めた方がいい．
前のHRP2-Vよりはずっと軽量でいいセットになったと思うので
このままで運ぶのがいいですね．

茶色の椅子にHRP2を座らせると地上からの高さは何センチくらいだろう．
アルファードには問題なく入っていた．
126cmだとアルファードは難しいかな．
明日にでも車を手に入れて調べてみるけども．

稲葉




2016年7月17日 17:22 Inaba Masayuki <inaba@i.u-tokyo.ac.jp>:

**Comment by k-kimura** [comment]
スロープは3号館地下にありました．おそらくこれだとおもいます．
![img_0504](https://cloud.githubusercontent.com/assets/8577781/16900240/15f35a04-4c5a-11e6-8f23-da4a249d462d.JPG)
幅も大丈夫そうですね．


> 茶色の椅子にHRP2を座らせると地上からの高さは何センチくらいだろう．

地面から台車上面までの高さと，地面から茶色の椅子座面までの高さを比べて見積ると，
おおよそ118cm(=126cm-8cm)くらいの高さになります．
これでしたら台車部分を外さないで，multisenseのヘルメット(簡単に外せる)を外すほうが入りやすくなるとおもいます．

参考までですが
http://lineup-cars.sakura.ne.jp/3978.html
によるとアルファード10系という車の荷台高さは120cmくらいなので，
ヘルメットを外して18号機の高さを115cmにすれば余裕がありそうです．

もし余裕がなければ，アルファードのほうをドローン機体運搬用，
(借りれたら)ハイエースのほうを18号機運搬用と分ければよさそうにおもいます．

**Comment by tongtybj** [comment]
別のスレッドで合宿についての議論があったので、
まとめてこっちに張り付けておきます。

稲葉先生から: 
///////////////////////////////////////////////////////////////
合宿中に天板のマークをその場で作ったり
するための色紙，テープ，カッターなどの
材料を忘れないようにしておく必要がありますね．

必要なものは発注します．
養生カラーテープはいろいろ使えると思うから
買っておきます．

アルファードは息子から借りるので大丈夫です．
２１日夜から２３日１２時まで名古屋出張なので
２３日１３時ころに大学に来て，
１５時ころに大学を出発という予定になりそうです．

天気予報では
２３，２４日は雨になりそうな気配だけども
雨の時にはどうするかの計画も考えておく必要
ありますね．屋内の施設，セミナー室を
調べておくのかな．

研究室のmobile WiFiがあるので来週渡します．
///////////////////////////////////////////////////////

**Comment by tongtybj** [comment]
追記:

今気づいたけども，
合宿のスレッドは，start-jsk/xxx
というのでgithubで公開されているメールリストね？

アルファードの話や研究室内の部屋の番号など
ローカルな話は外に公開されるところではないところで
やりとりしたい．
記録としてリストを作り編集してゆくというものに
公開のサイトにおいてあるのはいいと思うけども．

稲葉

**Comment by tongtybj** [comment]
> アルファードの話や研究室内の部屋の番号など
> ローカルな話は外に公開されるところではないところで
> やりとりしたい．

gamilでもちゃんとしたスレッドを立てましょう。
プレーシートや管理表を含めて、
今週前半中に準備体制を整っていきたいと思っています。

溝花君、古田君、よろしくお願いします。
