### ISSUE TITLE
ドローンのdashboardを作りたい

### ISSUE THREAD

**Issue by furushchev** [start-jsk/jsk_mbzirc#90]
> ドローン用のdashboardを作りたいだけど、
> pr2_dashboardを参考にしてつくればいいのかな？

**Comment by furushchev** [comment]
@tongtybj 
https://github.com/ros-visualization/rqt_robot_plugins/tree/master/rqt_robot_dashboard
というdashboard用のwidgetを集めたものがありますので、これに対応するtopicを送るノードを作っていくのだと思います。

**Comment by tongtybj** [comment]
@furushchev 
ありがとう！
やってみます

**Comment by YoheiKakiuchi** [comment]
hrpsys(jaxon)は以下のようにして作っています。
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/hrpsys_ros_bridge/hrpsys_dashboard.py
https://github.com/jsk-ros-pkg/trans_system/blob/master/trans_ros_bridge/src/trans_ros_bridge/trans_dashboard.py

**Comment by tongtybj** [comment]
@YoheiKakiuchi 
垣内さん、ありがとうございます。
ちなみに、go home機能が必要なのですが、
家みたいなアイコンはあったりしますか？

**Comment by YoheiKakiuchi** [comment]
あったような気もしますが、pr2-dashboardをインストールして、
/opt/ros の下のアイコンを探してみて下さい。

必要なアイコンは作らないと、jaxonみたいに、同じアイコンが並んで区別がつかなくなったりします。

**Comment by tongtybj** [comment]
@YoheiKakiuchi 

ここにあるのが全部でしょうか。
https://github.com/ros-visualization/rqt_robot_plugins/tree/master/rqt_robot_dashboard/images

自分で作る場合は,必ずsvg形式じゃないとだめでしょうか。

**Comment by YoheiKakiuchi** [comment]
> ここにあるのが全部でしょうか。
> https://github.com/ros-visualization/rqt_robot_plugins/tree/master/rqt_robot_dashboard/images

そうかもしれない。

形式は、pngでもいいような気がする。
svgもpngもlibraoffice drawで作ることができると思います。

**Comment by tongtybj** [comment]
@YoheiKakiuchi 

なるほどですね。いくつか作ってみます。

**Comment by k-okada** [comment]
find /usr/share/icons

--
◉ Kei Okada

**Comment by tongtybj** [comment]
@k-okada 

ありがとうございます。いろいろ見つかりました！
